# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlist',
            name='Remember_me',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postlist',
            name='accept_Terms_Conditions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postlist',
            name='image',
            field=models.FileField(default=None, upload_to='home/Downloads/'),
        ),
        migrations.AlterField(
            model_name='postlist',
            name='states',
            field=models.CharField(choices=[('Delhi', 'DELHI'), ('Mumbai', 'MUMBAI'), ('Agra', 'AGRA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postlist',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
