# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20180122_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlist',
            name='name',
        ),
        migrations.AddField(
            model_name='postlist',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postlist',
            name='Email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='postlist',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=56),
        ),
    ]
