# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_auto_20180124_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.FileField(upload_to='home/Downloads/'),
        ),
    ]
