# Generated by Django 2.0.4 on 2018-04-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_auto_20180412_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
