# Generated by Django 2.0.4 on 2018-04-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_postmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='sortchoices',
            field=models.CharField(choices=[('username', 'By username A-Z'), ('-username', 'By username Z-A'), ('Email', 'By Email A-Z'), ('-Email', 'By Email Z-A')], max_length=10),
        ),
    ]
